### ISSUE TITLE
flow level flow control

### ISSUE THREAD

**Issue by adami** [CodeInKit/flows#2]
current implementation requires that the action itself will set the __flows done/jump values in order to influence the flow.
but actions need to be simple, mindless components.
so if i have a function "getUserFromDb" that is in 2 flows, where 1 flow needs to jump to another flow if the user is not in the DB, and the other flow needs to continue, it is up to the function itself to "know" which flow it's on in order to respond properly.

instead, i suggest letting pre_action and post_action return an object (not mandatory, original will be used if not), and checking for flow changes (done/jump) following the calls to pre_action and post_action.
this may also mean allowing only 1 pre_action and post_action hooks to be registered.
it may also mean that it might be wise to allow registering a specific pre_action and/or post_action hooks per flow action.

what do you think?

**Comment by amitmtrn** [comment]
Hi @adami,
I agree with you that an action should be simple and should not be aware of anything flow related.
But I also want the flows to be as simple as possible.
Therefore I'm not sure there is a different approach where you can jump from flow to flow but in action itself.
If you want to separate the jumping mechanism by using action hooks it can be archived by high order action.
example: 
```js

function action(data) {

}

function highOrderAction(config) {
  return (data) => {
  // pre_action
  const returnedData = action(data);
  // post_action
  return returnedData;
  }
}

flows.register('flow', [highOrderAction()])
```

**Comment by adami** [comment]
yes, sounds ok to me
